### ISSUE TITLE
Update Elementor classes to current namespaces

### ISSUE THREAD

**Issue by vlastimilott** [tommusrhodus/TommusRhodus-Framework#2]
There are old class names, i.e.  Scheme_Color::get_type() in elementor-blocks/jumpstart/counter-block.php

Please replace Scheme_Color with \Elementor\Core\Schemes\Color.

thasnk

**Comment by bobbydank** [comment]
I created a gist with a patch you can apply to your theme or as a plugin. It will fix the error: https://gist.github.com/bobbydank/38e8dfb9a980ea9c87adba69db72e117

**Comment by tommusrhodus** [comment]
This was updated a few days ago https://github.com/tommusrhodus/TommusRhodus-Framework/commit/b84504b62c79291b883be2e2f7ab44092db7c801 👍 

Delete the plugin from your site, and let the theme re-install it from "appearance => install plugins", this will always give you the latest version.
